'''Search criteria tree for advanced search'''

from __future__ import absolute_import

def load():
    return _DATA


_DATA = [{'children': [{'code': u'233', 'label': u'1000'},
               {'code': u'234', 'label': u'2000'},
               {'code': u'235', 'label': u'3000'}],
  'label': u'Most frequent spoken words'},
 {'children': [{'code': u'236', 'label': u'1000'},
               {'code': u'237', 'label': u'2000'},
               {'code': u'238', 'label': u'3000'}],
  'label': u'Most frequent written words'},
 {'children': [{'code': u'332', 'label': u'Picture'},
               {'code': u'333', 'label': u'Sound effect'}],
  'label': u'Multimedia'},
 {'children': [{'code': u'334', 'label': u'adjective'},
               {'code': u'335', 'label': u'adverb'},
               {'code': u'336', 'label': u'auxiliary verb'},
               {'code': u'337', 'label': u'conjunction'},
               {'code': u'338', 'label': u'determiner'},
               {'code': u'339', 'label': u'interjection'},
               {'code': u'340', 'label': u'modal verb'},
               {'children': [{'code': 'u1', 'label': 'uncountable'}],
                'code': u'341',
                'label': u'noun'},
               {'code': u'342', 'label': u'number'},
               {'code': u'343', 'label': u'phrasal verb'},
               {'code': u'344', 'label': u'predeterminer'},
               {'code': u'345', 'label': u'prefix'},
               {'code': u'346', 'label': u'preposition'},
               {'code': u'347', 'label': u'pronoun'},
               {'code': u'348', 'label': u'suffix'},
               {'code': u'349', 'label': u'verb'}],
  'label': u'Part of speech'},
 {'children': [{'code': u'350', 'label': u'biblical'},
               {'code': u'351', 'label': u'formal'},
               {'code': u'352', 'label': u'humorous'},
               {'code': u'353', 'label': u'informal'},
               {'code': u'354', 'label': u'law'},
               {'code': u'355', 'label': u'literary'},
               {'code': u'356', 'label': u'medical'},
               {'code': u'357', 'label': u'not polite'},
               {'code': u'358', 'label': u'old use'},
               {'code': u'359', 'label': u'old-fashioned'},
               {'code': u'360', 'label': u'spoken'},
               {'code': u'361', 'label': u'taboo'},
               {'code': u'362', 'label': u'technical'},
               {'code': u'363', 'label': u'trademark'},
               {'code': u'364', 'label': u'written'}],
  'label': u'Register'},
 {'children': [{'code': 'u2', 'label': 'British English'},
               {'code': 'u3', 'label': 'American English'}],
  'label': 'Region'},
 {'code': u'426', 'label': u'Academic Word List'},
 {'children': [{'children': [{'code': u'19', 'label': u'Architecture'},
                             {'code': u'20', 'label': u'Literature'},
                             {'children': [{'code': u'22',
                                            'label': u'Film'},
                                           {'code': u'23',
                                            'label': u'Television & Radio'}],
                              'code': u'21',
                              'label': u'Media'},
                             {'children': [{'code': u'25',
                                            'label': u'Dance'},
                                           {'code': u'26',
                                            'label': u'Music'},
                                           {'code': u'27',
                                            'label': u'Theatre'}],
                              'code': u'24',
                              'label': u'Performing'},
                             {'children': [{'code': u'29',
                                            'label': u'Design'},
                                           {'code': u'30',
                                            'label': u'Painting and Drawing'},
                                           {'code': u'31',
                                            'label': u'Sculpture'}],
                              'code': u'28',
                              'label': u'Visual'}],
                'code': u'18',
                'label': u'ARTS'},
               {'children': [{'children': [{'code': u'34',
                                            'label': u'Advertising & Marketing'},
                                           {'code': u'35',
                                            'label': u'Business Management'},
                                           {'code': u'36',
                                            'label': u'Companies'},
                                           {'code': u'37',
                                            'label': u'Offices'},
                                           {'code': u'38',
                                            'label': u'Trade'}],
                              'code': u'33',
                              'label': u'Basics'},
                             {'children': [{'code': u'40',
                                            'label': u'Conditions of Employment'},
                                           {'code': u'41',
                                            'label': u'Labour Relations/Unions'},
                                           {'code': u'42',
                                            'label': u'Wages'}],
                              'code': u'39',
                              'label': u'Employment'},
                             {'children': [{'code': u'44',
                                            'label': u'Banking'},
                                           {'code': u'45',
                                            'label': u'Insurance'},
                                           {'code': u'46',
                                            'label': u'Loans'},
                                           {'code': u'47',
                                            'label': u'Stocks & Shares'}],
                              'code': u'43',
                              'label': u'Finance'},
                             {'code': u'48', 'label': u'Occupations'}],
                'code': u'32',
                'label': u'BUSINESS'},
               {'children': [{'code': u'50', 'label': u'Colours'},
                             {'code': u'51', 'label': u'Shapes/Patterns'},
                             {'code': u'52', 'label': u'Odours'},
                             {'code': u'53', 'label': u'Textures/Sounds'},
                             {'code': u'54', 'label': u'Tastes'}],
                'code': u'49',
                'label': u'COLOURS & SOUNDS'},
               {'children': [{'children': [{'code': u'57',
                                            'label': u'Hair & Beauty'},
                                           {'code': u'58',
                                            'label': u'Clothes'},
                                           {'code': u'59',
                                            'label': u'Jewellery'}],
                              'code': u'56',
                              'label': u'Clothes & Fashion'},
                             {'children': [{'code': u'61',
                                            'label': u'Cooking'},
                                           {'code': u'62',
                                            'label': u'Drink'},
                                           {'code': u'63',
                                            'label': u'Food Dish'},
                                           {'code': u'64',
                                            'label': u'Nutrition'},
                                           {'code': u'65',
                                            'label': u'Tobacco'},
                                           {'code': u'66',
                                            'label': u'Utensils'}],
                              'code': u'60',
                              'label': u'Food'},
                             {'children': [{'code': u'68',
                                            'label': u'Board Games'},
                                           {'code': u'69',
                                            'label': u'Cards'},
                                           {'code': u'70',
                                            'label': u'Darts'},
                                           {'code': u'71',
                                            'label': u'Gambling'},
                                           {'code': u'72',
                                            'label': u'Other Games'}],
                              'code': u'67',
                              'label': u'Games'},
                             {'children': [{'code': u'74',
                                            'label': u'Babies'},
                                           {'code': u'75',
                                            'label': u'Cleaning'},
                                           {'code': u'76',
                                            'label': u'Furniture'},
                                           {'code': u'77',
                                            'label': u'House'},
                                           {'code': u'78',
                                            'label': u'Pets'},
                                           {'code': u'79',
                                            'label': u'Toys'}],
                              'code': u'73',
                              'label': u'Household'},
                             {'children': [{'code': u'81',
                                            'label': u'Gardening'},
                                           {'code': u'82',
                                            'label': u'Sewing & Knitting'},
                                           {'code': u'83',
                                            'label': u'Outdoor'},
                                           {'code': u'84',
                                            'label': u'Tourism'}],
                              'code': u'80',
                              'label': u'Leisure'},
                             {'code': u'85', 'label': u'Nature'},
                             {'children': [{'code': u'87',
                                            'label': u'American Football'},
                                           {'code': u'88',
                                            'label': u'Baseball'},
                                           {'code': u'89',
                                            'label': u'Cricket'},
                                           {'code': u'90',
                                            'label': u'Football'},
                                           {'code': u'91',
                                            'label': u'Golf'},
                                           {'code': u'92',
                                            'label': u'Horses'},
                                           {'code': u'93',
                                            'label': u'Other Sports'},
                                           {'code': u'94',
                                            'label': u'Swimming'},
                                           {'code': u'95',
                                            'label': u'Tennis'}],
                              'code': u'86',
                              'label': u'Sport'}],
                'code': u'55',
                'label': u'DAILY LIFE'},
               {'children': [{'code': u'97', 'label': u'Astronomy'},
                             {'children': [{'code': u'99',
                                            'label': u'Animals'},
                                           {'code': u'100',
                                            'label': u'Birds'},
                                           {'code': u'101',
                                            'label': u'Fish'},
                                           {'code': u'102',
                                            'label': u'Human'},
                                           {'code': u'103',
                                            'label': u'Insects'},
                                           {'code': u'104',
                                            'label': u'Microbes/Genetics/Biochem'},
                                           {'code': u'105',
                                            'label': u'Plants'}],
                              'code': u'98',
                              'label': u'Biology'},
                             {'children': [{'code': u'107',
                                            'label': u'Compounds'},
                                           {'code': u'108',
                                            'label': u'Elements'},
                                           {'code': u'109',
                                            'label': u'Plastics'}],
                              'code': u'106',
                              'label': u'Chemistry'},
                             {'children': [{'code': u'111',
                                            'label': u'Geology'},
                                           {'code': u'112',
                                            'label': u'Meteorology'},
                                           {'code': u'113',
                                            'label': u'Oceanography'}],
                              'code': u'110',
                              'label': u'Earth Sciences'},
                             {'children': [{'code': u'115',
                                            'label': u'Numbers'},
                                           {'code': u'116',
                                            'label': u'Statistics'}],
                              'code': u'114',
                              'label': u'Maths'},
                             {'children': [{'code': u'118',
                                            'label': u'Electricity'},
                                           {'code': u'119',
                                            'label': u'Optics'}],
                              'code': u'117',
                              'label': u'Physics'}],
                'code': u'96',
                'label': u'HARD SCIENCE'},
               {'children': [{'code': u'121',
                              'label': u'Alternative Medicine'},
                             {'code': u'122', 'label': u'Birth'},
                             {'children': [{'code': u'124',
                                            'label': u'Drug Culture'}],
                              'code': u'123',
                              'label': u'Drugs/Medicines'},
                             {'code': u'125', 'label': u'Hospital'},
                             {'code': u'126',
                              'label': u'Illness & Disability'},
                             {'code': u'127',
                              'label': u'Nurses, Doctors, etc'},
                             {'code': u'128',
                              'label': u'Psychology/Psychiatry'},
                             {'code': u'129', 'label': u'Death'}],
                'code': u'120',
                'label': u'MEDICINE'},
               {'children': [{'children': [{'code': u'132',
                                            'label': u'Currencies'},
                                           {'code': u'133',
                                            'label': u'Tax'},
                                           {'code': u'134',
                                            'label': u'Welfare'}],
                              'code': u'131',
                              'label': u'Economics'},
                             {'children': [{'code': u'136',
                                            'label': u'Citizenship'},
                                           {'code': u'137',
                                            'label': u'Officials'},
                                           {'code': u'138',
                                            'label': u'Parliaments'}],
                              'code': u'135',
                              'label': u'Government'},
                             {'children': [{'code': u'140',
                                            'label': u'Army'},
                                           {'code': u'141',
                                            'label': u'Defence'},
                                           {'code': u'142',
                                            'label': u'Navy'},
                                           {'code': u'143',
                                            'label': u'Airforce'},
                                           {'code': u'144',
                                            'label': u'Weapons'}],
                              'code': u'139',
                              'label': u'Military'},
                             {'children': [{'code': u'146',
                                            'label': u'Groupings'},
                                           {'code': u'147',
                                            'label': u'Policies'},
                                           {'code': u'148',
                                            'label': u'Voting'}],
                              'code': u'145',
                              'label': u'Politics'}],
                'code': u'130',
                'label': u'POLITICS'},
               {'children': [{'code': u'150', 'label': u'Folklore'},
                             {'code': u'151', 'label': u'Mythology'},
                             {'children': [{'code': u'153',
                                            'label': u'Astrology'},
                                           {'code': u'154',
                                            'label': u'Magic'}],
                              'code': u'152',
                              'label': u'Occult'},
                             {'code': u'155', 'label': u'Philosophy'},
                             {'children': [{'code': u'157',
                                            'label': u'Buddhism'},
                                           {'code': u'158',
                                            'label': u'Christianity'},
                                           {'code': u'159',
                                            'label': u'Hinduism'},
                                           {'code': u'160',
                                            'label': u'Islam'},
                                           {'code': u'161',
                                            'label': u'Judaism'}],
                              'code': u'156',
                              'label': u'Religion'}],
                'code': u'149',
                'label': u'RELIGION & THOUGHT'},
               {'children': [{'children': [{'code': u'164',
                                            'label': u'Nationality & Race'}],
                              'code': u'163',
                              'label': u'Anthropology'},
                             {'children': [{'code': u'166',
                                            'label': u'Bombs & Terrorism'},
                                           {'code': u'167',
                                            'label': u'Crime'},
                                           {'code': u'168',
                                            'label': u'Jail & punishment'},
                                           {'code': u'169',
                                            'label': u'Law'},
                                           {'code': u'170',
                                            'label': u'Police'}],
                              'code': u'165',
                              'label': u'Crime & Law'},
                             {'children': [{'code': u'172',
                                            'label': u'College'},
                                           {'code': u'173',
                                            'label': u'Pre School'},
                                           {'code': u'174',
                                            'label': u'School'},
                                           {'code': u'175',
                                            'label': u'Training'}],
                              'code': u'171',
                              'label': u'Education'},
                             {'children': [{'code': u'177',
                                            'label': u'Environment & waste'}],
                              'code': u'176',
                              'label': u'Geography'},
                             {'code': u'178', 'label': u'History'},
                             {'children': [{'code': u'180',
                                            'label': u'Letters & punctuation'},
                                           {'code': u'181',
                                            'label': u'Grammar'},
                                           {'code': u'182',
                                            'label': u'Languages'}],
                              'code': u'179',
                              'label': u'Linguistics'},
                             {'children': [{'code': u'184',
                                            'label': u'Children'},
                                           {'code': u'185',
                                            'label': u'Family'},
                                           {'code': u'186',
                                            'label': u'Organizations'},
                                           {'code': u'187',
                                            'label': u'Race Relations'},
                                           {'code': u'188',
                                            'label': u'Women'},
                                           {'code': u'189',
                                            'label': u'Youth'}],
                              'code': u'183',
                              'label': u'Sociology'},
                             {'code': u'190', 'label': u'Archaeology'}],
                'code': u'162',
                'label': u'SOCIETY'},
               {'children': [{'children': [{'code': u'193',
                                            'label': u'Crops'},
                                           {'code': u'194',
                                            'label': u'Forestry'},
                                           {'code': u'195',
                                            'label': u'Soil'}],
                              'code': u'192',
                              'label': u'Agriculture'},
                             {'children': [{'code': u'197',
                                            'label': u'Buildings'},
                                           {'code': u'198',
                                            'label': u'Construction'}],
                              'code': u'196',
                              'label': u'Building'},
                             {'children': [{'code': u'200',
                                            'label': u'Broadcasting'},
                                           {'code': u'201',
                                            'label': u'Mail'},
                                           {'code': u'202',
                                            'label': u'Newspapers/Printing/Publishing'},
                                           {'code': u'203',
                                            'label': u'Photography'},
                                           {'code': u'204',
                                            'label': u'Recording'},
                                           {'code': u'205',
                                            'label': u'Telephone/Telegraph'}],
                              'code': u'199',
                              'label': u'Communications'},
                             {'code': u'206', 'label': u'Computers'},
                             {'children': [{'code': u'208',
                                            'label': u'Civil'},
                                           {'code': u'209',
                                            'label': u'Electrical'},
                                           {'code': u'210',
                                            'label': u'Mechanical'}],
                              'code': u'207',
                              'label': u'Engineering'},
                             {'children': [{'code': u'212',
                                            'label': u'Crafts'},
                                           {'code': u'213',
                                            'label': u'Factories'},
                                           {'code': u'214',
                                            'label': u'Glass'},
                                           {'code': u'215',
                                            'label': u'Material & Textiles'},
                                           {'code': u'216',
                                            'label': u'Pottery & Ceramics'}],
                              'code': u'211',
                              'label': u'Industry'},
                             {'children': [{'code': u'218',
                                            'label': u'Chronology'},
                                           {'code': u'219',
                                            'label': u'Temperature'}],
                              'code': u'217',
                              'label': u'Measurement'},
                             {'children': [{'code': u'221',
                                            'label': u'Electricity'},
                                           {'code': u'222',
                                            'label': u'Gas/Coal/Oil'},
                                           {'code': u'223',
                                            'label': u'Wind/Water/Sun'}],
                              'code': u'220',
                              'label': u'Power'},
                             {'children': [{'code': u'225',
                                            'label': u'Air'},
                                           {'code': u'226',
                                            'label': u'Bicycles/Carts/Horses'},
                                           {'code': u'227',
                                            'label': u'Motor Vehicles'},
                                           {'code': u'228',
                                            'label': u'Roads'},
                                           {'code': u'229',
                                            'label': u'Space'},
                                           {'code': u'230',
                                            'label': u'Trains & Railways'},
                                           {'code': u'231',
                                            'label': u'Water'}],
                              'code': u'224',
                              'label': u'Transport'},
                             {'code': u'232', 'label': u'Tools'}],
                'code': u'191',
                'label': u'TECHNOLOGY'}],
  'label': u'Subject'},
 {'children': [{'children': [{'code': u'368',
                              'label': u'architects, designers'},
                             {'code': u'369', 'label': u'artists'},
                             {'code': u'370', 'label': u'business'},
                             {'code': u'371', 'label': u'cinema, TV'},
                             {'code': u'372', 'label': u'crime'},
                             {'code': u'373', 'label': u'dancers'},
                             {'code': u'374',
                              'label': u'economy, finance'},
                             {'code': u'375', 'label': u'educators'},
                             {'code': u'376',
                              'label': u'engineers, inventors'},
                             {'code': u'377',
                              'label': u'explorers, navigators'},
                             {'code': u'378', 'label': u'fashion'},
                             {'code': u'379', 'label': u'heroes'},
                             {'code': u'380', 'label': u'lawyers, judges'},
                             {'code': u'381', 'label': u'writers'},
                             {'code': u'382', 'label': u'medical'},
                             {'code': u'383', 'label': u'military'},
                             {'code': u'384', 'label': u'music'},
                             {'code': u'385', 'label': u'philosophers'},
                             {'code': u'386', 'label': u'political'},
                             {'code': u'387', 'label': u'religious'},
                             {'code': u'388', 'label': u'royal'},
                             {'code': u'389', 'label': u'scientists'},
                             {'code': u'390',
                              'label': u'social reformers'},
                             {'code': u'391', 'label': u'sports'}],
                'code': u'365',
                'label': u'People'},
               {'children': [{'code': u'392', 'label': u'city'},
                             {'code': u'393', 'label': u'country'},
                             {'code': u'394', 'label': u'feature'},
                             {'code': u'395', 'label': u'region'},
                             {'code': u'396', 'label': u'site'}],
                'code': u'366',
                'label': u'Places'},
               {'children': [{'code': u'397',
                              'label': u'arts, architecture'},
                             {'code': u'398',
                              'label': u'business,commerce'},
                             {'code': u'399', 'label': u'calendar'},
                             {'code': u'400',
                              'label': u'ceremonies, traditions'},
                             {'code': u'401', 'label': u'cinema, TV'},
                             {'code': u'402', 'label': u'consumer goods'},
                             {'code': u'403', 'label': u'crime'},
                             {'code': u'404', 'label': u'dance companies'},
                             {'code': u'405',
                              'label': u'economy, finance'},
                             {'code': u'406', 'label': u'education'},
                             {'code': u'407', 'label': u'environmental'},
                             {'code': u'408', 'label': u'fiction'},
                             {'code': u'409', 'label': u'geographical'},
                             {'code': u'410', 'label': u'history'},
                             {'code': u'411', 'label': u'law'},
                             {'code': u'412', 'label': u'literature'},
                             {'code': u'413', 'label': u'medical'},
                             {'code': u'414', 'label': u'military'},
                             {'code': u'415', 'label': u'musical'},
                             {'code': u'416',
                              'label': u'mythological names'},
                             {'code': u'418', 'label': u'politics'},
                             {'code': u'419', 'label': u'religious'},
                             {'code': u'420', 'label': u'science'},
                             {'code': u'421', 'label': u'social'},
                             {'code': u'422', 'label': u'sports'},
                             {'code': u'423', 'label': u'theatre'},
                             {'code': u'424', 'label': u'transport'}],
                'code': u'367',
                'label': u'Other'}],
  'label': u'Culture'},
 {'children': [{'code': u'5', 'label': u'8th century'},
               {'code': u'6', 'label': u'9th century'},
               {'code': u'7', 'label': u'10th century'},
               {'code': u'8', 'label': u'11th century'},
               {'code': u'9', 'label': u'12th century'},
               {'code': u'10', 'label': u'13th century'},
               {'code': u'11', 'label': u'14th century'},
               {'code': u'12', 'label': u'15th century'},
               {'code': u'13', 'label': u'16th century'},
               {'code': u'14', 'label': u'17th century'},
               {'code': u'15', 'label': u'18th century'},
               {'code': u'16', 'label': u'19th century'},
               {'code': u'17', 'label': u'20th century'}],
  'label': u'Date'},
 {'children': [{'code': u'239', 'label': u'Afrikaans'},
               {'code': u'240', 'label': u'Aleut'},
               {'code': u'241', 'label': u'Algonquian'},
               {'code': u'242', 'label': u'American Spanish'},
               {'code': u'243', 'label': u'Anglo-French'},
               {'code': u'244', 'label': u'Arabic'},
               {'code': u'245', 'label': u'Aramaic'},
               {'code': u'246', 'label': u'Arawakan'},
               {'code': u'247', 'label': u'Australian Aboriginal'},
               {'code': u'248', 'label': u'Aymara'},
               {'code': u'249', 'label': u'Bantu'},
               {'code': u'250', 'label': u'Canadian French'},
               {'code': u'251', 'label': u'Carib'},
               {'code': u'252', 'label': u'Catalan'},
               {'code': u'253', 'label': u'Celtic'},
               {'code': u'254', 'label': u'Chinese'},
               {'code': u'255', 'label': u'Czech'},
               {'code': u'256', 'label': u'Danish'},
               {'code': u'257', 'label': u'Dharuk'},
               {'code': u'258', 'label': u'Dutch'},
               {'code': u'259', 'label': u'Egyptian'},
               {'code': u'260', 'label': u'English'},
               {'code': u'261', 'label': u'English dialect'},
               {'code': u'262', 'label': u'Flemish'},
               {'code': u'263', 'label': u'French'},
               {'code': u'264', 'label': u'French dialect'},
               {'code': u'265', 'label': u'German'},
               {'code': u'266', 'label': u'German dialect'},
               {'code': u'267', 'label': u'Germanic'},
               {'code': u'268', 'label': u'Greek'},
               {'code': u'269', 'label': u'Hawaiian'},
               {'code': u'270', 'label': u'Hebrew'},
               {'code': u'271', 'label': u'Hindi'},
               {'code': u'272', 'label': u'Hungarian'},
               {'code': u'273', 'label': u'Icelandic'},
               {'code': u'274', 'label': u'Irish Gaelic'},
               {'code': u'275', 'label': u'Italian'},
               {'code': u'276', 'label': u'Italian dialect'},
               {'code': u'277', 'label': u'Japanese'},
               {'code': u'278', 'label': u'Korean'},
               {'code': u'279', 'label': u'Late Greek'},
               {'code': u'280', 'label': u'Late Latin'},
               {'code': u'281', 'label': u'Latin'},
               {'code': u'282', 'label': u'Louisiana French'},
               {'code': u'283', 'label': u'Low German'},
               {'code': u'284', 'label': u'Malay'},
               {'code': u'285', 'label': u'Maori'},
               {'code': u'286', 'label': u'Medieval Greek'},
               {'code': u'287', 'label': u'Medieval Latin'},
               {'code': u'288', 'label': u'Mexican Spanish'},
               {'code': u'289', 'label': u'Middle Dutch'},
               {'code': u'290', 'label': u'Middle High German'},
               {'code': u'291', 'label': u'Middle Low German'},
               {'code': u'292', 'label': u'Modern Greek'},
               {'code': u'293', 'label': u'Modern Latin'},
               {'code': u'294', 'label': u'Nahuatl'},
               {'code': u'295', 'label': u'Narragansett'},
               {'code': u'296', 'label': u'Norwegian'},
               {'code': u'297', 'label': u'Ojibwa'},
               {'code': u'298', 'label': u'Old English'},
               {'code': u'299', 'label': u'Old French'},
               {'code': u'300', 'label': u'Old Irish'},
               {'code': u'301', 'label': u'Old Italian'},
               {'code': u'302', 'label': u'Old Norse'},
               {'code': u'303', 'label': u'Old North French'},
               {'code': u'304', 'label': u'Old Proven\xe7al'},
               {'code': u'305', 'label': u'Old Spanish'},
               {'code': u'306', 'label': u'Persian'},
               {'code': u'307', 'label': u'Pidgin English'},
               {'code': u'308', 'label': u'Polish'},
               {'code': u'309', 'label': u'Portuguese'},
               {'code': u'310', 'label': u'Proven\xe7al'},
               {'code': u'311', 'label': u'Quechua'},
               {'code': u'312', 'label': u'Romany'},
               {'code': u'313', 'label': u'Russian'},
               {'code': u'314', 'label': u'Sanskrit'},
               {'code': u'315', 'label': u'Scandinavian'},
               {'code': u'316', 'label': u'Scottish English'},
               {'code': u'317', 'label': u'Scottish Gaelic'},
               {'code': u'318', 'label': u'Spanish'},
               {'code': u'319', 'label': u'Swedish'},
               {'code': u'320', 'label': u'Taino'},
               {'code': u'321', 'label': u'Tamil'},
               {'code': u'322', 'label': u'Tibetan'},
               {'code': u'323', 'label': u'Tupi'},
               {'code': u'324', 'label': u'Turkish'},
               {'code': u'325', 'label': u'Urdu'},
               {'code': u'326', 'label': u'Virginia Algonquian'},
               {'code': u'327', 'label': u'Vulgar Latin'},
               {'code': u'328', 'label': u'Welsh'},
               {'code': u'329', 'label': u'West African'},
               {'code': u'330', 'label': u'Yiddish'},
               {'code': u'331', 'label': u'Zulu'}],
  'label': u'Language of origin'}]
